const labels=['Start','Gebäudeart','Dachform & Eindeckung','Standort','Dachfläche','Stromverbrauch','Bestandsanlage','Stromspeicher','Weiteres Zubehör','Wunschtermin','Berechnung'];
const s={step:0,max:0,project:'',building:'',roof:'',cover:'',plz:'',area:0,consumption:0,existing:'',existingKwp:0,existingModules:0,storage:'',storageSize:'auto',accessories:[],dateChoice:'',wishDate:'',products:[]};let master=[];
const $=id=>document.getElementById(id), panels=[...document.querySelectorAll('.panel')];
function initSteps(){ $('steps').innerHTML=labels.map((x,i)=>`<div class="step-item ${i?'locked':'active'}" data-i="${i}"><span class="num">${i}</span><span>${x}</span></div>`).join('');document.querySelectorAll('.step-item').forEach(el=>el.onclick=()=>{let i=+el.dataset.i;if(i<=s.max)show(i)})}
function choose(id,key,cb){$(id).addEventListener('click',e=>{let b=e.target.closest('button[data-v]');if(!b)return;[...$(id).querySelectorAll('button')].forEach(x=>x.classList.toggle('active',x===b));s[key]=b.dataset.v;cb?.(b.dataset.v);update()})}
function coverOptions(){let opts=s.roof==='Schrägdach'?['Dachziegel / Dachstein','Trapezblech','Stockschrauben / sonstige Befestigung']:['Ost/West-Ausrichtung','Süd-Ausrichtung'];$('coverTitle').textContent=s.roof==='Schrägdach'?'Eindeckung / Befestigung':'Ausrichtung';$('cover').innerHTML=opts.map(x=>`<button data-v="${x}">${x}</button>`).join('');$('coverBlock').classList.remove('hidden');s.cover='';choose('cover','cover')}
function storageReco(){let kwp=recommend().kwp, val=kwp<=6?5.1:kwp<=9?7.7:kwp<=12?10.2:12.8;$('storageReco').innerHTML=`<strong>Erste Empfehlung: ca. ${String(val).replace('.',',')} kWh</strong><br><span class="muted">Die Speichergröße wird in der nächsten Ausbaustufe noch genauer an Verbrauch und Anlagenleistung gekoppelt.</span>`;return val}
function accessoryDetails(){if(!s.accessories.length){$('accessoryDetails').classList.add('hidden');return}$('accessoryDetails').classList.remove('hidden');let h='<h3>Details zum Zubehör</h3>';if(s.accessories.includes('Wallbox'))h+=`<label>Wallbox-Ausführung<select id="wallbox"><option>11 kW ohne MID-Zähler</option><option>22 kW ohne MID-Zähler</option><option>11 kW mit MID-Zähler</option></select></label>`;if(s.accessories.includes('Zählerschrank'))h+=`<label>Zählerschrank<select id="cabinet"><option>EFH 110x55 cm – 1 Zählerplatz – ohne Bestückung</option><option>EFH 110x55 cm – 1 Zählerplatz – mit Bestückung</option><option>EFH 110x80 cm – 2 Zählerplätze – ohne Bestückung</option><option>EFH 110x80 cm – 2 Zählerplätze – mit Bestückung</option></select></label>`;if(s.accessories.includes('Notstrom'))h+=`<label>Notstrom / Fronius-Zubehör<select id="backup"><option>Netzumschaltbox Enwitec 20 kW</option><option>PV-Point</option><option>Backup Switch</option><option>Backup Controller</option></select></label>`;$('accessoryDetails').innerHTML=h}
function recommend(){let area=+s.area||0,cons=+s.consumption||0;let maxModules=Math.floor(area/2.05*.82), targetKwp=Math.max(3,Math.min(15,cons?cons/1000*1.65:6));if(s.existing==='Erweiterung gewünscht')targetKwp=Math.max(3,targetKwp-(+s.existingKwp||0));let targetModules=Math.ceil(targetKwp/.46),modules=Math.max(0,Math.min(maxModules,targetModules));let kwp=+(modules*.46).toFixed(2);return{maxModules,modules,kwp,targetKwp}}
function validate(){if(s.step===1)return !!s.building;if(s.step===2)return !!s.roof&&!!s.cover;if(s.step===3)return /^\d{5}$/.test(s.plz);if(s.step===4)return s.area>0;if(s.step===5)return s.consumption>0;if(s.step===6)return !!s.existing&&(s.existing!=='Erweiterung gewünscht'||s.existingKwp>0);if(s.step===7)return !!s.storage;if(s.step===9)return !!s.dateChoice||!!s.wishDate;return true}
function show(i){s.step=Math.max(0,Math.min(i,s.max));panels.forEach(p=>p.classList.toggle('active',+p.dataset.step===s.step));document.querySelectorAll('.step-item').forEach(el=>{let n=+el.dataset.i;el.classList.toggle('active',n===s.step);el.classList.toggle('locked',n>s.max)});$('prev').style.visibility=s.step===0?'hidden':'visible';$('next').style.display=s.step===10?'none':'';if(s.step===7&&s.storage==='Ja')storageReco();if(s.step===10)calculate();updateNext();window.scrollTo({top:0,behavior:'smooth'})}
function updateNext(){let ok=validate();$('next').disabled=!ok;$('next').style.opacity=ok?1:.45;$('stepHint').style.display=ok?'none':'block';$('stepHint').textContent='Bitte vervollständigen Sie die Angaben in diesem Schritt.'}
function update(){s.project=$('project').value.trim();s.plz=$('plz').value.trim();s.area=+$('area').value||0;s.consumption=+$('consumption').value||0;s.existingKwp=+$('existingKwp').value||0;s.existingModules=+$('existingModules').value||0;s.storageSize=$('storageSize').value;s.wishDate=$('wishDate').value;let r=recommend();let boxes=[['Projekt',s.project||'Keine Angabe'],['Gebäude',s.building||'Noch nicht gewählt'],['Dach',s.roof?(s.roof+(s.cover?' · '+s.cover:'')):'Noch nicht gewählt'],['Standort',s.plz||'PLZ offen'],['Dachfläche',s.area?`${s.area} m²`:'Noch offen'],['Stromverbrauch',s.consumption?`${s.consumption.toLocaleString('de-DE')} kWh/Jahr`:'Noch offen'],['Bestandsanlage',s.existing||'Noch nicht gewählt'],['Speicher',s.storage?(s.storage==='Ja'?'Gewünscht':'Nicht gewünscht'):'Noch nicht gewählt'],['Zubehör',s.accessories.length?s.accessories.join(' · '):'Noch nichts gewählt'],['Wunschtermin',s.wishDate?new Date(s.wishDate+'T00:00').toLocaleDateString('de-DE'):(s.dateChoice||'Noch offen')]];let html=boxes.map(x=>`<div class="summary-box"><b>${x[0]}</b><span>${x[1]}</span></div>`).join('');if(s.consumption&&s.area)html+=`<div class="summary-box reco"><b>Vorläufige Empfehlung</b><span>${r.kwp.toLocaleString('de-DE')} kWp · ${r.modules} Module${s.storage==='Ja'?` · Speicher ca. ${String(storageReco()).replace('.',',')} kWh`:''}</span></div>`;$('summary').innerHTML=html;updateNext()}
function findProduct(test){return master.find(p=>test(p.artikelbezeichnung.toLowerCase()))}
function add(list,p,qty=1){if(p)list.push({...p,qty})}
function calculate(){let r=recommend(),list=[];if(s.roof==='Schrägdach'){if(s.cover.includes('Trapez'))add(list,findProduct(n=>n.includes('schrägdachmontage mit trapez')),r.modules);else if(s.cover.includes('Stock'))add(list,findProduct(n=>n.includes('stockschrauben')),r.modules);else add(list,findProduct(n=>n==='schrägdachmontage'),r.modules)}else add(list,findProduct(n=>n.includes('flachdachmontage')&&(s.cover.includes('Ost/West')?n.includes('ost/west'):n.includes('süd'))),r.modules);
let wr=Math.max(3,Math.min(15,Math.ceil(r.kwp)));let pool=master.filter(p=>p.kategorie===(s.storage==='Ja'?'Hybrid-Wechselrichter':'Wechselrichter'));let wp=pool.find(p=>(+p.leistung_kw||0)>=wr)||pool.at(-1);add(list,wp);if(s.storage==='Ja'){let cap=s.storageSize==='auto'?storageReco():+s.storageSize;let sp=master.filter(p=>p.kategorie==='Speicher').find(p=>Math.abs((+p.kapazitaet_kwh||0)-cap)<.2);add(list,sp)}
if(s.accessories.includes('Wallbox'))add(list,findProduct(n=>n.includes('11,0 kw wattpilot')&&n.includes('ohne mid')));if(s.accessories.includes('Zählerschrank'))add(list,findProduct(n=>n.includes('zählerschrank efh standard')));if(s.accessories.includes('Optimierer'))add(list,findProduct(n=>n.includes('tigo optimierer')),r.modules);if(s.accessories.includes('Notstrom'))add(list,findProduct(n=>n.includes('netzumsschaltbox')||n.includes('netzumschaltbox')));if(s.accessories.includes('Wärmepumpenvorbereitung'))add(list,findProduct(n=>n.includes('wärmepumpenanschluss')));if(s.accessories.includes('Gerüst'))add(list,findProduct(n=>n.includes('einrüstung')),1);s.products=list;
$('recommendation').innerHTML=`<strong>Empfohlene Anlagenkonfiguration</strong><div class="metric-grid"><div class="metric"><span>PV-Leistung</span><br><b>${r.kwp.toLocaleString('de-DE')} kWp</b></div><div class="metric"><span>Module</span><br><b>${r.modules}</b></div><div class="metric"><span>Max. Dachbelegung</span><br><b>${r.maxModules}</b></div><div class="metric"><span>Speicher</span><br><b>${s.storage==='Ja'?String(s.storageSize==='auto'?storageReco():s.storageSize).replace('.',',')+' kWh':'Nein'}</b></div></div><p>Die Empfehlung berücksichtigt in dieser ersten Version die nutzbare Dachfläche und den Jahresverbrauch. Pro Modul werden vorläufig 460 Wp und rund 2,05 m² angesetzt.</p>`;
$('resultBody').innerHTML=list.map((p,i)=>{let price=+String(p.preis).replace(',','.');let ph=price>=99999;return `<tr><td><input type="checkbox" checked></td><td>${p.artikelbezeichnung}</td><td>${p.qty}</td><td>${p.einheit}</td><td class="${ph?'price-placeholder':''}">${ph?'Preis offen':price.toLocaleString('de-DE',{style:'currency',currency:'EUR'})}</td></tr>`}).join('')||'<tr><td colspan="5">Noch keine passenden Positionen ermittelt.</td></tr>'}
async function load(){let t=await fetch('tga-master.csv').then(r=>r.text());let lines=t.replace(/^\uFEFF/,'').trim().split(/\r?\n/);let h=lines.shift().split(';');master=lines.map(line=>{let a=line.split(';'),o={};h.forEach((k,i)=>o[k]=a[i]||'');return o})}
initSteps();choose('building','building');choose('roof','roof',coverOptions);choose('existing','existing',v=>{$('existingDetails').classList.toggle('hidden',v!=='Erweiterung gewünscht')});choose('storage','storage',v=>{$('storageDetails').classList.toggle('hidden',v!=='Ja');if(v==='Ja')storageReco()});choose('dateChoice','dateChoice');choose('consumptionQuick','_q',v=>{$('consumption').value=v;s.consumption=+v;update()});$('accessories').onclick=e=>{let b=e.target.closest('button[data-v]');if(!b)return;let v=b.dataset.v;b.classList.toggle('active');s.accessories=b.classList.contains('active')?[...s.accessories,v]:s.accessories.filter(x=>x!==v);accessoryDetails();update()};['project','plz','area','consumption','existingKwp','existingModules','storageSize','wishDate'].forEach(id=>$(id).addEventListener('input',update));$('next').onclick=()=>{if(!validate())return;s.max=Math.max(s.max,s.step+1);show(s.step+1)};$('prev').onclick=()=>show(s.step-1);$('clear').onclick=()=>{if(confirm('Möchten Sie wirklich alle Eingaben löschen?'))location.reload()};load().catch(console.error);update();show(0);
